import { Brand, Product } from "@/types";

export const brands: Brand[] = [
  { id: "burberry", name: "Burberry", origin: "europeo" },
  { id: "calvin-klein", name: "Calvin Klein", origin: "americano" },
  { id: "dolce-gabbana", name: "Dolce & Gabbana", origin: "europeo" },
  { id: "guess", name: "Guess 1981", origin: "americano" },
  { id: "hugo-boss", name: "Hugo Boss", origin: "europeo" },
  { id: "jpgaultier", name: "Jean Paul Gaultier", origin: "europeo" },
  { id: "lattafa", name: "Lattafa", origin: "arabe" },
  { id: "paco-rabanne", name: "Paco Rabanne", origin: "europeo" },
  { id: "ralph-lauren", name: "Ralph Lauren", origin: "americano" },
  { id: "ysl", name: "Yves Saint Laurent", origin: "europeo" },
  { id: "armaf", name: "Armaf", origin: "arabe" },
  { id: "azzaro", name: "Azzaro", origin: "europeo" },
  { id: "rasasi", name: "Rasasi", origin: "arabe" },
  { id: "ajmal", name: "Ajmal", origin: "arabe" },
  { id: "al-haramain", name: "Al Haramain", origin: "arabe" },
  { id: "armani", name: "Giorgio Armani", origin: "europeo" },
  { id: "chanel", name: "Chanel", origin: "europeo" },
  { id: "dior", name: "Dior", origin: "europeo" },
  { id: "versace", name: "Versace", origin: "europeo" },
  { id: "tom-ford", name: "Tom Ford", origin: "americano" },
  { id: "lancome", name: "Lancôme", origin: "europeo" },
  { id: "fragrance-world", name: "Fragrance World", origin: "arabe" },
  { id: "maison-al-hambra", name: "Maison Al Hambra", origin: "arabe" },
  { id: "mugler", name: "Thierry Mugler", origin: "europeo" },
  { id: "lolita-lempicka", name: "Lolita Lempicka", origin: "europeo" },
  { id: "montblanc", name: "Montblanc", origin: "europeo" },
  { id: "odyssey", name: "Odyssey", origin: "arabe" },
  { id: "french-avenue", name: "French Avenue", origin: "europeo" },
];

function b(id: string): Brand {
  return brands.find((brand) => brand.id === id)!;
}


export const products: Product[] = [];

// ── Productos reales del catálogo ──────────────────────────────────────────

const realProducts: Product[] = [
  {
    id: "r1", slug: "azzaro-most-wanted-edp-intense",
    name: "The Most Wanted EDP Intense", brand: b("azzaro"),
    price: 60990, gender: "hombre", category: "oriental", priceRange: "media",
    description: "Seductor e intenso. Una fragancia amaderada y especiada para el hombre que sabe lo que quiere.",
    notes: { top: ["Cardamomo", "Lavanda"], heart: ["Cedro", "Palo Santo"], base: ["Vainilla", "Ámbar"] },
    sizes: [50], images: ["https://cosmetic.cl/cdn/shop/files/Azzaro-The-Most-Wanted-Parfum-100-ml_600x.png?v=1731083682"],
    isFeatured: false, isBestseller: true, isRecommended: true, isNew: false, stock: 10,
  }, // r1 AZZARO ✓ bestseller
  {
    id: "r2", slug: "bad-famme-parfum",
    name: "Bad Famme Parfum", brand: b("fragrance-world"),
    price: 16990, gender: "mujer", category: "floral", priceRange: "popular",
    description: "Una fragancia femenina audaz y seductora de larga duración.",
    notes: { top: ["Pera", "Bergamota"], heart: ["Rosa", "Jazmín"], base: ["Almizcle", "Pachulí"] },
    sizes: [100], images: ["https://productosdelujo.cl/cdn/shop/files/Disenosintitulo_44_88e9d37c-c1b7-4e27-9cb6-d352c941c1be.jpg?v=1702227336&width=700"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 20,
  },
  {
    id: "r3", slug: "burberry-her-50ml",
    name: "Burberry Her", brand: b("burberry"),
    price: 76990, gender: "mujer", category: "floral", priceRange: "lujo",
    description: "Una fragancia frutal y floral inspirada en la energía de Londres. Fresca, vibrante y moderna.",
    notes: { top: ["Bayas rojas", "Grosella negra"], heart: ["Violeta", "Jazmín"], base: ["Almizcle", "Sándalo"] },
    sizes: [50], images: ["https://media.falabella.com/falabellaCL/50070703_2/w=1200,h=1200,fit=pad"],
    isFeatured: true, isBestseller: false, isRecommended: true, isNew: false, stock: 12,
  },
  {
    id: "r4", slug: "burberry-her-100ml-edt",
    name: "Burberry Her EDT", brand: b("burberry"),
    price: 86990, gender: "mujer", category: "floral", priceRange: "lujo",
    description: "La versión Eau de Toilette en tamaño grande. Ligera, fresca y contemporánea.",
    notes: { top: ["Bayas rojas", "Limón"], heart: ["Violeta", "Geranio"], base: ["Almizcle blanco"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_825926-MLC74751337667_022024-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 8,
  },
  {
    id: "r5", slug: "burberry-hero-edt",
    name: "Burberry Hero EDT", brand: b("burberry"),
    price: 46990, gender: "hombre", category: "amaderado", priceRange: "media",
    description: "Cedro y notas marinas. Una fragancia masculina que evoca fuerza y elegancia natural.",
    notes: { top: ["Bergamota", "Pimienta negra"], heart: ["Cedro japonés", "Notas marinas"], base: ["Almizcle", "Vetiver"] },
    sizes: [50], images: ["https://www.eliteperfumes.cl/cdn/shop/files/burberry-53086071980402.jpg?v=1732574051&width=900"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 15,
  },
  {
    id: "r6", slug: "burberry-touch-women",
    name: "Burberry Touch for Women", brand: b("burberry"),
    price: 38990, gender: "mujer", category: "floral", priceRange: "media",
    description: "Suave y romántica. Una fragancia floral y amaderada con corazón de algodón.",
    notes: { top: ["Mandarina", "Coriandro"], heart: ["Magnolia", "Rosa"], base: ["Cedro", "Sándalo"] },
    sizes: [100], images: ["https://silkperfumes.cl/cdn/shop/products/burberry-touch-for-women-edp-100ml.jpg?v=1707763523&width=1125"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 10,
  },
  {
    id: "r7", slug: "burberry-mini-estuche",
    name: "Burberry Mini Estuche x4", brand: b("burberry"),
    price: 49990, gender: "unisex", category: "floral", priceRange: "media",
    description: "Set de 4 miniaturas de las fragancias más icónicas de Burberry. Perfecto para regalo.",
    notes: { top: ["Varios"], heart: ["Varios"], base: ["Varios"] },
    sizes: [5], images: ["https://cl-cenco-pim-resizer.ecomm.cencosud.com/unsafe/adaptive-fit-in/640x0/filters:quality(75)/prd-cl/product-medias/d52c4f10-9dbe-4acf-a1dc-7c1cf221ca6f/MKXTYYEX71/MKXTYYEX71-1/1773929906589-MKXTYYEX71-1-2.jpg"],
    isFeatured: true, isBestseller: true, isRecommended: true, isNew: true, stock: 18,
  },
  {
    id: "r8", slug: "ck-in2u-toilette",
    name: "CK IN2U Toilette", brand: b("calvin-klein"),
    price: 15990, gender: "unisex", category: "citrico", priceRange: "popular",
    description: "Fresca y despreocupada. Una fragancia joven y vibrante con notas cítricas y amaderadas.",
    notes: { top: ["Bergamota", "Naranja", "Limón"], heart: ["Cacao", "Heliotropo"], base: ["Cedro", "Almizcle"] },
    sizes: [50], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_853873-MLA45824998136_052021-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 25,
  },
  {
    id: "r9", slug: "ck-in2u-hombre",
    name: "CK IN2U Him EDT", brand: b("calvin-klein"),
    price: 19990, gender: "hombre", category: "citrico", priceRange: "popular",
    description: "Energizante y moderno. Una fragancia masculina fresca para el día a día.",
    notes: { top: ["Lima", "Bergamota"], heart: ["Cedro", "Notas digitales"], base: ["Almizcle blanco"] },
    sizes: [50], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_910757-MLA51801449772_102022-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 20,
  },
  {
    id: "r10", slug: "ck-euphoria-parfum",
    name: "Euphoria Parfum", brand: b("calvin-klein"),
    price: 48990, gender: "mujer", category: "oriental", priceRange: "media",
    description: "Sensual y misterioso. Granadas, uva negra y crisantemo en una composición intensa.",
    notes: { top: ["Granada", "Uva negra"], heart: ["Jazmín", "Loto"], base: ["Almizcle", "Madera cremosa", "Ámbar"] },
    sizes: [100], images: ["https://mundoaromas.cl/cdn/shop/files/EUPHORIA.webp?v=1759169305"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 14,
  },
  {
    id: "r11", slug: "club-de-nuit-woman",
    name: "Club de Nuit Woman Parfum", brand: b("armaf"),
    price: 27990, gender: "mujer", category: "floral", priceRange: "popular",
    description: "Elegante y seductora. Una fragancia femenina de larga duración con notas florales y amizcladas.",
    notes: { top: ["Piña", "Bergamota"], heart: ["Rosa", "Jazmín"], base: ["Almizcle", "Pachulí", "Vainilla"] },
    sizes: [105], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_926902-MLU73204723748_122023-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 22,
  },
  {
    id: "r12", slug: "club-de-nuit-iconic",
    name: "Club de Nuit Iconic EDP", brand: b("armaf"),
    price: 44990, gender: "unisex", category: "oriental", priceRange: "media",
    description: "La versión icónica. Una fragancia unisex intensa y sofisticada para ocasiones especiales.",
    notes: { top: ["Piña", "Limón", "Bergamota"], heart: ["Rosa", "Jazmín", "Naranja"], base: ["Almizcle", "Ámbar", "Cedro"] },
    sizes: [105], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_926902-MLU73204723748_122023-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 18,
  },
  {
    id: "r13", slug: "dg-light-blue-homme-edt",
    name: "Light Blue Pour Homme EDT", brand: b("dolce-gabbana"),
    price: 57990, gender: "hombre", category: "acuatico", priceRange: "media",
    description: "El Mediterráneo en un frasco. Fresco, marino y vibrante. Un clásico masculino italiano.",
    notes: { top: ["Bergamota siciliana", "Enebro", "Pomelo"], heart: ["Pimienta chilena", "Álamo"], base: ["Almizcle", "Incienso", "Madera de Oud"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_774178-MLA47614355879_092021-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 16,
  },
  {
    id: "r14", slug: "dg-light-blue-homme-toilette-100ml",
    name: "Light Blue Pour Homme Toilette 100 ML", brand: b("dolce-gabbana"),
    price: 59990, gender: "hombre", category: "acuatico", priceRange: "media",
    description: "La versión Toilette premium en tamaño generoso. Frescura mediterránea de larga duración.",
    notes: { top: ["Bergamota", "Pomelo", "Enebro"], heart: ["Pimienta", "Madera de Gaiac"], base: ["Almizcle", "Cedro"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_865360-MLA87291710285_072025-F.webp"],
    isFeatured: false, isBestseller: true, isRecommended: true, isNew: false, stock: 8,
  },
  {
    id: "r15", slug: "dg-light-blue-summer-vibes",
    name: "Light Blue Summer Vibes Toilette", brand: b("dolce-gabbana"),
    price: 62990, gender: "hombre", category: "acuatico", priceRange: "media",
    description: "Edición limitada veraniega. Más fresca y tropical que la original, perfecta para el verano.",
    notes: { top: ["Bergamota", "Kiwi", "Menta"], heart: ["Lemon verbena", "Notas marinas"], base: ["Almizcle", "Cedro blanco"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_628631-MLA82562689571_022025-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 10,
  },
  {
    id: "r16", slug: "fragrance-world-ador",
    name: "Ador EDP", brand: b("fragrance-world"),
    price: 20990, gender: "mujer", category: "floral", priceRange: "popular",
    description: "Una fragancia femenina dulce y elegante con notas florales y vainilladas de larga duración.",
    notes: { top: ["Pera", "Bergamota"], heart: ["Rosa", "Jazmín"], base: ["Vainilla", "Almizcle"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_662927-MLA79968225277_102024-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 25,
  },
  {
    id: "r17", slug: "guess-1981-indigo-mujer",
    name: "Guess 1981 Indigo Mujer", brand: b("guess"),
    price: 32990, gender: "mujer", category: "floral", priceRange: "media",
    description: "Juvenil y romántica. Una fragancia floral frutal inspirada en el espíritu libre de California.",
    notes: { top: ["Naranja de sangre", "Pera", "Frambuesa"], heart: ["Magnolia", "Rosa"], base: ["Almizcle blanco", "Cedro"] },
    sizes: [100], images: ["https://multimarcasperfumes.cl/cdn/shop/products/9486_5000x.jpg?v=1598578794"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 15,
  },
  {
    id: "r18", slug: "hugo-dark-blue",
    name: "Hugo Dark Blue Toilette", brand: b("hugo-boss"),
    price: 29990, gender: "hombre", category: "acuatico", priceRange: "popular",
    description: "Fresco y urbano. Notas cítricas y amaderadas para el hombre moderno y activo.",
    notes: { top: ["Lima", "Petitgrain", "Pimienta roja"], heart: ["Artemisa", "Geranio"], base: ["Cedro", "Sándalo", "Almizcle"] },
    sizes: [75], images: ["https://www.lodoro.cl/cdn/shop/files/Disenosintitulo-2025-07-30T170530.385.png?v=1753909545&width=1000"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 20,
  },
  {
    id: "r19", slug: "hugo-iced",
    name: "Hugo Iced Toilette", brand: b("hugo-boss"),
    price: 32000, gender: "hombre", category: "acuatico", priceRange: "media",
    description: "Intensamente frío y refrescante. Una explosión de frescura ártica para el verano.",
    notes: { top: ["Menta ártica", "Limón helado"], heart: ["Manzana verde", "Geranio"], base: ["Cedro", "Almizcle frío"] },
    sizes: [75], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_605539-MLU75803446107_042024-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 15,
  },
  {
    id: "r20", slug: "jpg-le-male-125ml",
    name: "Le Male EDT 125ml", brand: b("jpgaultier"),
    price: 95990, gender: "hombre", category: "oriental", priceRange: "lujo",
    description: "El icónico frasco marinero. Una fragancia masculina atemporal con lavanda, vainilla y menta.",
    notes: { top: ["Menta", "Lavanda", "Cardamomo"], heart: ["Canela", "Flor de naranjo", "Cuero"], base: ["Vainilla", "Almizcle", "Sándalo"] },
    sizes: [125], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_896419-MLU73836909302_012024-F.webp"],
    isFeatured: true, isBestseller: false, isRecommended: true, isNew: false, stock: 12,
  },
  {
    id: "r21", slug: "fragrance-world-just-aswad",
    name: "Just Aswad EDP", brand: b("fragrance-world"),
    price: 19990, gender: "hombre", category: "arabe", priceRange: "popular",
    description: "Inspiración árabe oscura y profunda. Oud y especias en una fragancia masculina intensa.",
    notes: { top: ["Especias", "Bergamota"], heart: ["Oud", "Rosa"], base: ["Ámbar", "Almizcle"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_830432-MLC92277088526_092025-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 20,
  },
  {
    id: "r22", slug: "lattafa-pride-nebras",
    name: "Pride Nebras", brand: b("lattafa"),
    price: 35990, gender: "unisex", category: "arabe", priceRange: "media",
    description: "La estrella del orgullo. Una fragancia árabe unisex luminosa con oud y notas florales.",
    notes: { top: ["Azafrán", "Bergamota"], heart: ["Oud", "Rosa árabe"], base: ["Ámbar", "Almizcle", "Sándalo"] },
    sizes: [100], images: ["https://silkperfumes.cl/cdn/shop/files/lattafa-pride-nebras-edp-100ml-Silk-Perfumes.png?v=1747754908&width=1125"],
    isFeatured: false, isBestseller: true, isRecommended: true, isNew: true, stock: 18,
  },
  {
    id: "r23", slug: "lattafa-yara-collection-mini",
    name: "Yara Collection Mini x4", brand: b("lattafa"),
    price: 24990, gender: "mujer", category: "arabe", priceRange: "popular",
    description: "Set de 4 miniaturas de la colección Yara. Ideal para descubrir las fragancias árabes de Lattafa.",
    notes: { top: ["Bergamota", "Pera"], heart: ["Rosa", "Jazmín"], base: ["Almizcle", "Ámbar", "Vainilla"] },
    sizes: [5], images: ["https://www.lodoro.cl/cdn/shop/files/Disenosintitulo-2025-11-21T131840.249.png?v=1763741929&width=1000"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 30,
  },
  {
    id: "r24", slug: "dg-light-blue-capri",
    name: "Light Blue Capri In Love EDP", brand: b("dolce-gabbana"),
    price: 71990, gender: "mujer", category: "acuatico", priceRange: "lujo",
    description: "Edición limitada inspirada en la isla de Capri. Fresca, sensual y mediterránea.",
    notes: { top: ["Limón de Amalfi", "Manzana verde"], heart: ["Jazmín", "Rosa"], base: ["Almizcle", "Cedro"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_712444-MLC105903265392_022026-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 8,
  },
  {
    id: "r25", slug: "lolita-lempicka-mon-premier",
    name: "Mon Premier Parfum EDP", brand: b("lolita-lempicka"),
    price: 57990, gender: "mujer", category: "oriental", priceRange: "media",
    description: "Dulce y mágico. El emblemático frasco manzana de Lolita Lempicka con vainilla y regaliz.",
    notes: { top: ["Anis", "Violeta"], heart: ["Iris", "Amendrón"], base: ["Vetiver", "Vainilla", "Musgo de roble"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_798531-MLA84761712677_052025-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 10,
  },
  {
    id: "r26", slug: "burberry-london-mujer",
    name: "London EDP Mujer", brand: b("burberry"),
    price: 44990, gender: "mujer", category: "floral", priceRange: "media",
    description: "La esencia de Londres. Una fragancia femenina romántica con notas florales y orientales.",
    notes: { top: ["Naranja de sangre", "Peonia"], heart: ["Rosa", "Lirio"], base: ["Vetiver", "Sándalo", "Almizcle"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_640757-MLC52416544653_112022-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 12,
  },
  {
    id: "r27", slug: "maison-al-hambra-salvo-intense",
    name: "Salvo Intense EDP", brand: b("maison-al-hambra"),
    price: 15990, gender: "unisex", category: "arabe", priceRange: "popular",
    description: "Profundo y envolvente. Una fragancia árabe unisex de larga duración con oud y ámbar.",
    notes: { top: ["Especias orientales"], heart: ["Oud", "Cuero"], base: ["Ámbar", "Vainilla", "Almizcle"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_910092-MLA85298834656_062025-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 25,
  },
  {
    id: "r28", slug: "montblanc-femme-individuelle",
    name: "Femme Individuelle Toilette", brand: b("montblanc"),
    price: 32990, gender: "mujer", category: "floral", priceRange: "media",
    description: "Sofisticada e independiente. Una fragancia floral frutal para la mujer de hoy.",
    notes: { top: ["Mandarina", "Bergamota", "Melocotón"], heart: ["Rosa", "Jazmín", "Lila"], base: ["Sándalo", "Almizcle", "Cedro"] },
    sizes: [75], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_930120-MLU75458435127_032024-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 10,
  },
  {
    id: "r29", slug: "mugler-alien-hypersense",
    name: "Alien Hypersense EDP", brand: b("mugler"),
    price: 49990, gender: "mujer", category: "oriental", priceRange: "media",
    description: "Misterioso y sensual. La versión más intensa de Alien con jasmine solar y madera blanca.",
    notes: { top: ["Jasmine solar"], heart: ["Madera blanca", "Curcuma"], base: ["Ámbar cósmico", "Cachemira"] },
    sizes: [30], images: ["https://www.ofertaperfumes.cl/cdn/shop/files/d1c735dc-b46c-4de0-9d25-dcfe20db6279-perfume_alien_hypersense_thierry_mugler_dama_edp_30_ml.jpg?v=1770852927&width=980"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: true, stock: 8,
  },
  {
    id: "r30", slug: "odyssey-mandarin-sky",
    name: "Mandarin Sky Parfum", brand: b("odyssey"),
    price: 35990, gender: "unisex", category: "citrico", priceRange: "media",
    description: "Fresco y luminoso. Notas cítricas y amaderadas para cualquier ocasión.",
    notes: { top: ["Mandarina", "Bergamota", "Limón"], heart: ["Cedro", "Musgo"], base: ["Almizcle", "Ámbar"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_806818-MLM73982503686_012024-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 15,
  },
  {
    id: "r31", slug: "paco-rabanne-lady-million-fabulous",
    name: "Lady Million Fabulous Intense EDP", brand: b("paco-rabanne"),
    price: 70990, gender: "mujer", category: "floral", priceRange: "lujo",
    description: "Fabulosa e irresistible. La versión más intensa y dulce de Lady Million con notas de caramelo.",
    notes: { top: ["Neroli", "Azafrán"], heart: ["Flor de Almendra", "Rosa"], base: ["Patchouli", "Caramelo", "Vainilla"] },
    sizes: [80], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_648938-MLA53832654768_022023-F.webp"],
    isFeatured: true, isBestseller: false, isRecommended: true, isNew: false, stock: 10,
  },
  {
    id: "r32", slug: "polo-deep-blue-parfum",
    name: "Polo Deep Blue Parfum", brand: b("ralph-lauren"),
    price: 102990, gender: "hombre", category: "acuatico", priceRange: "lujo",
    description: "Las profundidades del océano. La fragancia marina más intensa de Ralph Lauren.",
    notes: { top: ["Bergamota de mar", "Cedro marino"], heart: ["Ambroxan", "Notas marinas"], base: ["Madera de gaiac", "Almizcle"] },
    sizes: [125], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_627727-MLA80623976638_112024-F.webp"],
    isFeatured: true, isBestseller: false, isRecommended: true, isNew: false, stock: 9,
  },
  {
    id: "r33", slug: "polo-red-edp",
    name: "Polo Red EDP", brand: b("ralph-lauren"),
    price: 89990, gender: "hombre", category: "especiado", priceRange: "lujo",
    description: "Audaz y apasionado. La fragancia roja de Ralph Lauren con notas de café y sándalo.",
    notes: { top: ["Pomelo rojo", "Albahaca"], heart: ["Café", "Azafrán"], base: ["Sándalo", "Ámbar"] },
    sizes: [75], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_614749-MLA80886881493_112024-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 12,
  },
  {
    id: "r34", slug: "dg-q-mujer",
    name: "Q EDP Mujer", brand: b("dolce-gabbana"),
    price: 84990, gender: "mujer", category: "floral", priceRange: "lujo",
    description: "La nueva fragancia icónica de Dolce&Gabbana. Floral, sensual y contemporánea.",
    notes: { top: ["Bergamota", "Pimienta rosa"], heart: ["Rosa damascena", "Iris"], base: ["Sándalo", "Vainilla", "Almizcle"] },
    sizes: [100], images: ["https://media.falabella.com/falabellaCL/80144232_2/w=1200,h=1200,fit=pad"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: true, stock: 8,
  },
  {
    id: "r35", slug: "ralph-lauren-big-pony-2",
    name: "Big Pony 2 for Women", brand: b("ralph-lauren"),
    price: 35990, gender: "mujer", category: "floral", priceRange: "media",
    description: "Fresca y deportiva. Una fragancia femenina ligera y jovial para el día a día.",
    notes: { top: ["Bergamota", "Lima", "Rhubarbo"], heart: ["Peonia", "Rosa"], base: ["Almizcle blanco", "Cedro"] },
    sizes: [100], images: ["https://i5.walmartimages.cl/asr/c1c426e4-e851-41af-b700-bfa173b8c1a5.0c68607a4e7f6d0b28ded9c4f60c0ea5.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF"],
    isFeatured: false, isBestseller: false, isRecommended: false, isNew: false, stock: 15,
  },
  {
    id: "r36", slug: "ralph-lauren-polo-blue-75ml",
    name: "Polo Blue EDT 75ml", brand: b("ralph-lauren"),
    price: 85990, gender: "hombre", category: "acuatico", priceRange: "lujo",
    description: "El clásico de los clásicos. Fresco, acuático y sofisticado. El perfume del polo y la elegancia americana.",
    notes: { top: ["Pepino", "Mandarina", "Albahaca"], heart: ["Melón", "Jazmín", "Geranio"], base: ["Almizcle", "Suede", "Cedro"] },
    sizes: [75], images: ["https://dbs.cl/media/catalog/product/r/h/rhl-02291_img2.jpg?optimize=low&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 14,
  },
  {
    id: "r37", slug: "ralph-lauren-club-new-york",
    name: "Ralph's Club New York EDP 110 ML", brand: b("ralph-lauren"),
    price: 95000, gender: "hombre", category: "especiado", priceRange: "lujo",
    description: "El glamour de Nueva York. Una fragancia masculina sofisticada con iris y madera.",
    notes: { top: ["Bergamota", "Melocotón"], heart: ["Iris", "Lavanda"], base: ["Cedro", "Almizcle", "Vetiver"] },
    sizes: [110], images: ["https://cosmetic.cl/cdn/shop/files/Perfume-Ralph-S-Club-New-York-EDP-110-ml-Ralph-Lauren_600x.png?v=1761738045"],
    isFeatured: true, isBestseller: true, isRecommended: true, isNew: false, stock: 10,
  },
  {
    id: "r38", slug: "versace-dylan-turquoise",
    name: "Dylan Turquoise EDT", brand: b("versace"),
    price: 79990, gender: "mujer", category: "acuatico", priceRange: "lujo",
    description: "El Mediterráneo femenino de Versace. Fresco, tropical y vibrante como el mar turquesa.",
    notes: { top: ["Yuzu", "Mandarina", "Kumquat"], heart: ["Flor de sandía", "Iris"], base: ["Almizcle", "Lentisco"] },
    sizes: [50], images: ["https://i.ebayimg.com/images/g/O~8AAeSwIs9pWIBX/s-l1600.webp"],
    isFeatured: false, isBestseller: true, isRecommended: true, isNew: false, stock: 11,
  },
  {
    id: "r39", slug: "vulcan-feu-french-avenue",
    name: "Vulcan Feu French Avenue 100 ML", brand: b("french-avenue"),
    price: 40990, gender: "hombre", category: "especiado", priceRange: "media",
    description: "Intenso y magnético. Una fragancia masculina de inspiración francesa con carácter volcánico.",
    notes: { top: ["Bergamota", "Pimienta"], heart: ["Cuero", "Cedro"], base: ["Ámbar", "Almizcle", "Vetiver"] },
    sizes: [100], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_615607-MLA103345029993_012026-F.webp"],
    isFeatured: false, isBestseller: true, isRecommended: true, isNew: false, stock: 12,
  },
  {
    id: "r40", slug: "ysl-libre-le-parfum",
    name: "Libre Le Parfum", brand: b("ysl"),
    price: 56990, gender: "mujer", category: "floral", priceRange: "media",
    description: "La libertad de ser una misma. Lavanda francesa y flor de naranjo en su versión más intensa.",
    notes: { top: ["Lavanda de Provenza"], heart: ["Flor de naranjo", "Jazmín"], base: ["Vainilla de Madagascar", "Almizcle"] },
    sizes: [30], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_715914-MLA50836518526_072022-F.webp"],
    isFeatured: true, isBestseller: false, isRecommended: true, isNew: false, stock: 10,
  },
  {
    id: "r41", slug: "armaf-club-de-nuit-untold",
    name: "Club de Nuit Untold", brand: b("armaf"),
    price: 44990, gender: "unisex", category: "amaderado", priceRange: "media",
    description: "Una fragancia unisex sofisticada y versátil. Notas amaderadas con un toque fresco y especiado de larga duración.",
    notes: { top: ["Bergamota", "Limón", "Pomelo"], heart: ["Geranio", "Cedro", "Ciprés"], base: ["Almizcle", "Patchouli", "Ámbar"] },
    sizes: [105], images: ["https://http2.mlstatic.com/D_NQ_NP_2X_897800-MLA54976209914_042023-F.webp"],
    isFeatured: false, isBestseller: false, isRecommended: true, isNew: false, stock: 15,
  },
];

products.push(...realProducts);

export const featuredProducts = products.filter((p) => p.isFeatured);
export const bestsellerProducts = products.filter((p) => p.isBestseller);
export const newProducts = products.filter((p) => p.isNew);

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("es-CL", {
    style: "currency",
    currency: "CLP",
    maximumFractionDigits: 0,
  }).format(price);
}
